import { Agent } from "node:https";

const DEFAULT_CIPHERS = [
  "ECDHE-ECDSA-CHACHA20-POLY1305",
  "ECDHE-RSA-CHACHA20-POLY1305",
  "ECDHE-ECDSA-AES128-GCM-SHA256",
  "ECDHE-RSA-AES128-GCM-SHA256",
  "ECDHE-ECDSA-AES256-GCM-SHA384",
  "ECDHE-RSA-AES256-GCM-SHA384",
  "ECDHE-ECDSA-AES128-SHA",
  "ECDHE-RSA-AES128-SHA",
  "ECDHE-ECDSA-AES256-SHA",
  "ECDHE-RSA-AES256-SHA",
  "AES128-GCM-SHA256",
  "AES256-GCM-SHA384",
  "AES128-SHA",
  "AES256-SHA",
  "DES-CBC3-SHA",
  "TLS_CHACHA20_POLY1305_SHA256",
  "TLS_AES_128_GCM_SHA256",
  "TLS_AES_256_GCM_SHA384",
];

const DEFAULT_MIN_VERSION = "TLSv1.2";

const DEFAULT_HONOR_CIPHER_ORDER = true;

export const getHttpsAgent = (ciphers, honorCipherOrder, minVersion) =>
  new Agent({
    ciphers: ciphers ?? DEFAULT_CIPHERS.join(":"),
    honorCipherOrder: honorCipherOrder ?? DEFAULT_HONOR_CIPHER_ORDER,
    minVersion: minVersion ?? DEFAULT_MIN_VERSION,
  });
